version: 2

updates:
  # Maintain dependencies for Ruby
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - cdalvaro
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - cdalvaro
    open-pull-requests-limit: 10
