name: Rubocop

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: latest
          bundler-cache: true

      - name: Run rubocop checks
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          use_bundler: true
          reporter: github-pr-review
