name: Advent of Code 2023 - Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  SKIP_SLOW_TESTS: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test puzzles
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: latest
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
